#!/bin/sh -Cue
#.help
# % [TARGET [OPT..] [ARG..]]
#
# Run Pyr.  If TARGET is "-" or omitted, use custom path and module.  All options are passed unchanged to Pyr.

is_interact() {
    while [ $# -gt 0 ]; do
        case "$1" in
            --) shift; break ;;
            --*) shift ;;
            -?*) shift ;;
            *) break ;;
            esac
        done
    [ $# = 0 ] || [ x"$1" = x- ]
    }

# modify variables as required
self="$(readlink -f -- "$0")"
pyr="${self%/*/*}/cmd/pyr"
if is_interact "$@"; then
    interact_path="$self-lib"
    interact_main="user_console"
    set -- -a"$0" -p"$interact_path" --interact="$interact_main" "$@"
    fi
exec "$pyr" "$@"
