#!/bin/sh -ue
#.help
# Run Pyr with custom interactive console.

### Modify these variables:
# path to Pyr
pyr="$(dirname "$0")/../pyr"
# directory containing interact_main (and any others desired) added to sys.path
interact_path="$0-lib"
# entry point
interact_main="user_console"
###


is_interact() {
    while [ $# -gt 0 ]; do
        case "$1" in
            --) shift; break ;;
            --*) shift ;;
            -?*) shift ;;
            *) break ;;
        esac
    done
    [ $# = 0 ] || [ x"$1" = x- ]
}
if is_interact "$@"; then
    set -- -p"$interact_path" --interact="$interact_main" "$@"
fi
exec "$pyr" "$@"
